Train:
  gpu : 1
  batch_size : 24
  model : openseg_pre_train
  epoch : 150
  learning_rate : 0.003
  num_points : 40000
  optimizer : Adam
  manual_seed : 2023
  log_dir : 
  decay_rate : 0.0004
  config_name : openseg_pre_train.yaml
  train_data_path : /data/xuxiaoxu/code/openvocabulary/ovdet_2d/openscene/data/scannet_3d/train
  val_data_path : /data/xuxiaoxu/code/openvocabulary/ovdet_2d/openscene/data/scannet_3d/val
  pesudo_label_path : /data/xuxiaoxu/code/openvocabulary/ovdet_2d/3DSS-VLG/vlm_ps_generation/vlm_ps/openseg
  train_openseg_embedding_path : /data/xuxiaoxu/code/openvocabulary/ovdet_2d/openscene/test_process
  val_openseg_embedding_path : /data/xuxiaoxu/code/openvocabulary/ovdet_2d/openscene/data/scannet_multiview_openseg