DATA:
  data_root: /data/xuxiaoxu/code/openvocabulary/ovdet_2d/openscene/data/scannet_3d
  data_root_2d_fused_feature: /data/xuxiaoxu/code/openvocabulary/ovdet_2d/openscene/data/scannet_multiview_openseg
  feature_2d_extractor: openseg
  classes: 20
  aug: True
  voxel_size: 0.02
  input_color: True
  use_shm: False
  
DISTILL:
  arch_3d: MinkUNet18A
  ignore_label: 255
  train_gpu: [2,3]
  workers: 6  # data loader workers
  batch_size: 8  # batch size for training
  batch_size_val: 2  # batch size for validation during training, memory and speed tradeoff
  base_lr: 0.0001
  loss_type: cosine # l1 | cosine
  loop: 5
  epochs: 100
  start_epoch: 0
  power: 0.9
  momentum: 0.9
  manual_seed: 1463
  print_freq: 10
  save_freq: 1
  save_path:
  resume:
  evaluate: True  # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend
  eval_freq: 1

TEST:
  split: val  # split in [train, val]
  prompt_eng: True
  mark_no_feature_to_unknown: True
  save_feature_as_numpy: False
  vis_input: False
  vis_pred: False
  vis_gt: False
  test_workers: 4
  test_gpu: [1]
  test_batch_size: 1
  test_repeats: 5
  model_path:
  save_folder:

Distributed:
  dist_url: tcp://127.0.0.1:6792
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  world_size: 1
  rank: 0