DATA:
  data_root: /data/xuxiaoxu/code/openvocabulary/ovdet_2d/openscene/data/scannet_3d
  data_root_2d_fused_feature: /data/xuxiaoxu/code/openvocabulary/ovdet_2d/openscene/test_process
  feature_2d_extractor: openseg
  classes: 20
  aug: False
  voxel_size: 0.02
  input_color: False
  use_shm: False

TEST:
  split: train  # split in [train, val]
  prompt_eng: True
  mark_no_feature_to_unknown: True
  save_feature_as_numpy: False
  test_workers: 0
  test_gpu: [0]
  test_batch_size: 1
  test_repeats: 1
  save_folder: /data/xuxiaoxu/code/openvocabulary/ovdet_2d/3DSS-VLG/vlm_ps_generation/vlm_ps/openseg  # the ps label save path
  save_folder :

Distributed:
  dist_url: tcp://127.0.0.1:6787
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  world_size: 1
  rank: 0